### ISSUE TITLE
get batchid in AuthResponse

### ISSUE THREAD

**Issue by seonzoo** [coatesap/omnipay-realex#11]
Hello, thanks for creating this gateway, it saved me a lot of time! 

I'm working on a project here that requires me to save the 'batchid' response from realex.

Would you be able to include it in a future release, or is there another way to retrieve this?

**Comment by coatesap** [comment]
Hi, yes it should be possible to do that. I haven't got the documentation to hand at the moment, but I believe you could probably add a `getBatchId()` method to the `AuthResponse` class. Assuming that 'batchid' is just another part of the XML that Realex returns, then the body of the method would be something like `return ($this->xml->batchid) ? (string)$this->xml->batchid : null;`

If you get that working, feel free to open a pull request, and I'll merge it in.
